
server:
  port: 9004

spring:
  application:
    name: book-service
  h2:
    console:
      enabled: true
  datasource:
    url: ${datasource.postgres}
    driver-class-name: ${driver.postgres}
    username: root
    password: 123
  jpa:

    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

eureka:
  instance:
    prefer-Ip-Address: true
    instance-id: ${server.address:localhost}:${spring.application.name}:${server.port}
  client:
    #    fetch-registry-with-eureka: true
    #    register-with-eureka: true
    service-url:
      defaultZone: http://jack:jack@localhost:8761/eureka/


datasource:
  mysql: jdbc:mysql://localhost:3307/transportation
  postgres: jdbc:postgresql://localhost:5432/books
  h2: jdbc:h2:mem:testdb

driver:
  mysql: com.mysql.cj.jdbc.Driver
  postgres: org.postgresql.Driver
  h2: org.h2.Driver