cloud:
  aws:
    credentials:
      access-key: AKIAVOFBO33JQF7O2CXS
      secret-key: 
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: filehandling

server:
  port: 9091