spring:
  security:
    basic:
      enabled: true
    user:
      name: jack
      password: jack
#      password: $2a$12$wNd4h8vpccdOgfkN8NdeqO8878Ieph6Nc5kBGWbp7Go5/ZnwQbf4G

  application:
    name: E-SERVER

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

#  servlet:
#    context-path: /
#  ssl:
#    enabled: true
#    key-alias: local_ssl
#    key-store: classpath:local-ssl.p12
#    key-store-type: PKCS12
##    key-password: Qwerty@123
#    key-store-password: Qwerty@123
