
spring:
  application:
    name: TRANSPORT-SERVICE
  datasource:
    driver-class-name: ${driver.mysql}
#    driver-class-name:
    url: ${datasource.mysql}
#    url:
    username : root
    password : root12345
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: jack
#      password: $2a$12$wNd4h8vpccdOgfkN8NdeqO8878Ieph6Nc5kBGWbp7Go5/ZnwQbf4G


eureka:
  client:
    prefer-same-zone-eureka: false
    serviceUrl:
#      defaultZone: http://10.0.61.80:8761/eureka/
      defaultZone: http://jack:jack@localhost:8761/eureka/
  instance:
    prefer-Ip-Address: true
    instance-id: ${server.address}:${spring.application.name}:${server.port}

server:
  address: 10.0.61.2
  port: 9090

datasource:
  mysql: jdbc:mysql://localhost:3306/transportation
  postgres: jdbc:postgresql://localhost:5432/transportation

driver:
  mysql: com.mysql.cj.jdbc.Driver
  postgres: org.postgresql.Driver