cloud:
  aws:
    credentials:
      access-key: AKIAW4BZ6PRLGLOE24MJ
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: practice.saurabh

server:
  port: 9015
